# Generated by Django 3.1 on 2020-09-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('evaluation', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleInReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=100)),
                ('round', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.FileField(blank=True, null=True, upload_to='')),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.article')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('orcid', models.BigIntegerField(default=1000000000000000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MCC',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(through='revista_cientifica.ArticleInReview', to='revista_cientifica.Article')),
                ('speciality', models.ManyToManyField(to='revista_cientifica.MCC')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_author', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.author')),
            ],
            options={
                'unique_together': {('author', 'article')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('checked', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='apps/revista_cientifica/media')),
                ('file_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.article')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='articles',
            field=models.ManyToManyField(through='revista_cientifica.Participation', to='revista_cientifica.Article'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleinreview',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.referee'),
        ),
        migrations.AddField(
            model_name='article',
            name='mcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revista_cientifica.mcc'),
        ),
        migrations.AlterUniqueTogether(
            name='articleinreview',
            unique_together={('referee', 'article', 'round')},
        ),
    ]
