# Generated by Django 3.1 on 2020-09-14 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
