# Generated by Django 3.0.3 on 2020-08-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleevaluation',
            old_name='state',
            new_name='evaluation',
        ),
    ]
