# Generated by Django 3.1.1 on 2020-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0002_auto_20201031_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(through='revista_cientifica.Participation', to='revista_cientifica.Author'),
        ),
    ]
