# Generated by Django 3.1 on 2020-08-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0002_auto_20200805_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='evaluation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articleinreview',
            name='evaluation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='articleinreview',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='articleinreview',
            unique_together={('referee', 'article', 'round')},
        ),
        migrations.DeleteModel(
            name='ArticleEvaluation',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
