# Generated by Django 3.1 on 2020-08-10 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0005_auto_20200810_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 10, 16, 57, 28, 129693, tzinfo=utc), null=True),
        ),
    ]
