# Generated by Django 3.1 on 2020-08-10 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0006_auto_20200810_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
