# Generated by Django 3.1 on 2020-08-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0012_auto_20200810_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ref',
        ),
    ]
