# Generated by Django 3.1 on 2020-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0014_notification_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinreview',
            name='evaluation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
