# Generated by Django 3.1 on 2020-08-15 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0015_auto_20200815_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinreview',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 15, 18, 39, 30, 312562, tzinfo=utc), null=True),
        ),
    ]
