# Generated by Django 3.1 on 2020-08-15 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0016_auto_20200815_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinreview',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
