# Generated by Django 3.1 on 2020-08-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0019_auto_20200816_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='articleinreview',
            name='start_date',
        ),
    ]
