# Generated by Django 3.1 on 2020-09-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0020_auto_20200825_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='ORCID',
            new_name='orcid',
        ),
    ]
