# Generated by Django 3.1.1 on 2020-09-08 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revista_cientifica', '0020_auto_20200816_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='articleinreview',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
